const topics=['systeme','zustandsraum','ruhelage','linearisierung','stabilitaet','steuerbarkeit','regler','beobachtbarkeit','beobachter'];
const names=['Dynamische Systeme','Zustandsraum','Ruhelage','Linearisierung','Stabilität','Steuerbarkeit','Zustandsregler','Beobachtbarkeit','Zustandsbeobachter'];
const saved=JSON.parse(localStorage.getItem('rus-progress')||'{}'),path=document.querySelector('#path');
topics.forEach((t,i)=>path.insertAdjacentHTML('beforeend',`<a href="#${t}" data-path="${t}"><b>${String(i+1).padStart(2,'0')}</b>${names[i]}</a>`));
function progress(){const n=topics.filter(t=>saved[t]).length,p=Math.round(n/topics.length*100);percent.textContent=p+' %';bar.style.width=p+'%';topics.forEach(t=>{document.querySelector(`[data-topic="${t}"]`).classList.toggle('complete',!!saved[t]);document.querySelector(`[data-path="${t}"]`).classList.toggle('complete',!!saved[t])})}
document.querySelectorAll('.done').forEach(b=>{if(saved[b.dataset.topic])b.textContent='Verstanden ✓';b.onclick=()=>{saved[b.dataset.topic]=!saved[b.dataset.topic];localStorage.setItem('rus-progress',JSON.stringify(saved));b.textContent=saved[b.dataset.topic]?'Verstanden ✓':'Als verstanden markieren';progress()}});progress();
menu.onclick=()=>document.querySelector('aside').classList.toggle('open');document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>document.querySelector('aside').classList.remove('open'));
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id))}),{rootMargin:'-25% 0px -65%'});document.querySelectorAll('main section[id]').forEach(s=>observer.observe(s));
document.querySelectorAll('.quiz').forEach(q=>q.querySelectorAll('button').forEach(b=>b.onclick=()=>{q.querySelectorAll('button').forEach(x=>x.className='');const ok=b.dataset.choice===q.dataset.answer;b.className=ok?'correct':'wrong';q.querySelector('p').textContent=ok?'Richtig: x₂ ist die erste Ableitung von x₁; seine Ableitung liefert die zweite Ableitung.':'Noch nicht. Das Ziel sind ausschließlich Gleichungen erster Ordnung.'}));

const exercises=[
['Systeme','Tankmodell','Ein Tank hat Zufluss q und Abfluss k√h. Wähle Zustand, Eingang und Zustandsgleichung.','Der Füllstand speichert die Vergangenheit.','x=h, u=q.','Mit Querschnitt S gilt: S·ḣ=q-k√h, also ḣ=(q-k√h)/S.'],
['Ruhelage','Arbeitspunkt','Bestimme u_R für ẋ=-3x+2u bei x_R=4.','Setze ẋ=0.','u_R=6.','0=-3·4+2u_R ⇒ 12=2u_R ⇒ u_R=6.'],
['Linearisierung','Jacobi-Matrix','Linearisiere ẋ=x²+u um x_R=2.','A ist ∂f/∂x am Arbeitspunkt.','A=4, B=1.','∂f/∂x=2x ⇒ A=4. ∂f/∂u=1 ⇒ B=1. Somit Δẋ=4Δx+Δu.'],
['Stabilität','Pole lesen','Ist ein System mit Polen -2 und 0.5 stabil?','Prüfe alle Realteile.','Instabil.','Der Pol 0.5 erzeugt e^(0.5t) und wächst. Ein positiver Realteil genügt für Instabilität.'],
['Steuerbarkeit','R-Matrix','Prüfe A=[[1,0],[0,2]], b=[1,0]ᵀ.','Berechne Ab und det(R).','Nicht vollständig steuerbar.','Ab=[1,0]ᵀ. R=[[1,1],[0,0]] hat Rang 1. Der zweite Zustand ist nicht erreichbar.'],
['Beobachtbarkeit','O-Matrix','Prüfe A=[[0,1],[0,0]], C=[1,0].','Berechne CA.','Vollständig beobachtbar.','CA=[0,1]. O ist die Einheitsmatrix und hat Rang 2.'],
['Regler','Polvorgabe','Welche Voraussetzung braucht die freie Polvorgabe?','Denke an die R-Matrix.','Vollständige Steuerbarkeit.','Nur bei Rang(R)=n kann der Eingang alle Moden beeinflussen und die Pole frei verschieben.'],
['Beobachter','Fehlerdynamik','Welche Matrix bestimmt den Schätzfehler?','Bilde e=x-x̂.','A-lC.','Subtraktion von Beobachter- und Systemgleichung liefert ė=(A-lC)e.']
];
exercises.forEach((e,i)=>exerciseGrid.insertAdjacentHTML('beforeend',`<article class="exercise-card"><span class="tag">${e[0]}</span><h3>${e[1]}</h3><p>${e[2]}</p><div class="reveal-buttons"><button data-show="h${i}">Tipp</button><button data-show="r${i}">Ergebnis</button><button data-show="s${i}">Rechenweg</button></div><div id="h${i}" class="reveal">${e[3]}</div><div id="r${i}" class="reveal"><b>${e[4]}</b></div><div id="s${i}" class="reveal">${e[5]}</div></article>`));
document.querySelectorAll('[data-show]').forEach(b=>b.onclick=()=>document.querySelector('#'+b.dataset.show).classList.toggle('show'));

const terms={Zustand:'Interne Größe, die zusammen mit dem Eingang die zukünftige Entwicklung festlegt.',Eingang:'Von außen wirkende oder steuerbare Größe u.',Ausgang:'Messbare oder interessierende Größe y.','Systemmatrix A':'Beschreibt die Eigendynamik eines linearen Systems.','Eingangsmatrix B/b':'Beschreibt, wie Eingänge auf Zustände wirken.','Ausgangsmatrix C/cᵀ':'Beschreibt, wie Zustände im Ausgang erscheinen.','Durchgriff D/d':'Unmittelbarer Einfluss von u auf y.',Ruhelage:'Zustand, in dem ẋ=0 gilt.',Arbeitspunkt:'Paar aus Ruhezustand x_R und passendem Eingang u_R.',Linearisierung:'Lokale Tangentennäherung eines nichtlinearen Systems.','Jacobi-Matrix':'Matrix aller ersten partiellen Ableitungen.','Eigenwert':'Kennzahl einer Dynamikmode; der Realteil entscheidet über Wachstum oder Abklingen.','Charakteristisches Polynom':'Polynom det(λI-A), dessen Nullstellen die Eigenwerte sind.','Asymptotisch stabil':'Alle Bewegungen kehren mit der Zeit zur Ruhelage zurück.',Instabil:'Mindestens eine Bewegung entfernt sich von der Ruhelage.',Steuerbarkeit:'Alle Zustände können mit dem Eingang beeinflusst werden.',Beobachtbarkeit:'Alle Zustände können aus dem Ausgang rekonstruiert werden.','Zustandsrückführung':'Regelgesetz, das den Zustand zurückführt.','Ackermann-Formel':'Formel zur Polvorgabe bei steuerbaren Eingrößensystemen.',Beobachter:'Dynamisches Modell, das nicht gemessene Zustände schätzt.',Fehlerdynamik:'Dynamik des Unterschieds e=x-x̂.'};
function renderGloss(q=''){glossary.innerHTML='';Object.entries(terms).filter(x=>x.join(' ').toLowerCase().includes(q.toLowerCase())).forEach(([k,v])=>glossary.insertAdjacentHTML('beforeend',`<div class="term"><b>${k}</b><p>${v}</p></div>`))}renderGloss();search.oninput=e=>renderGloss(e.target.value);

let calc='eigen';function matrixHTML(id,n,values){return `<div><b>${id}</b><div class="matrix c${n}">${values.map((v,i)=>`<input type="number" step="any" id="${id}${i}" value="${v}">`).join('')}</div></div>`}function vals(id,n){return Array.from({length:n},(_,i)=>+(document.querySelector('#'+id+i).value||0))}function f(x){return Math.abs(x)<1e-10?0:+x.toFixed(4)}
function draw(){let h=matrixHTML('A',2,[0,1,-2,-3]);if(calc==='control')h+=matrixHTML('b',1,[0,1]);if(calc==='observe')h+=matrixHTML('C',2,[1,0]);if(calc==='det3')h=matrixHTML('A',3,[1,2,3,0,1,4,5,6,0]);matrixInputs.innerHTML=`<div class="matrix-form">${h}</div>`;calcResult.innerHTML='<p>Bereit für deine Werte.</p>'}draw();
document.querySelectorAll('[data-calc]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-calc]').forEach(x=>x.classList.remove('active'));b.classList.add('active');calc=b.dataset.calc;draw()});
calculate.onclick=()=>{if(calc==='det3'){let a=vals('A',9),d=a[0]*(a[4]*a[8]-a[5]*a[7])-a[1]*(a[3]*a[8]-a[5]*a[6])+a[2]*(a[3]*a[7]-a[4]*a[6]);calcResult.innerHTML=`<div class="step">Entwicklung nach der ersten Zeile</div><div class="step">det(A) = ${a[0]}·(${a[4]}·${a[8]}-${a[5]}·${a[7]}) - ${a[1]}·(${a[3]}·${a[8]}-${a[5]}·${a[6]}) + ${a[2]}·(${a[3]}·${a[7]}-${a[4]}·${a[6]})</div><b>det(A) = ${f(d)}</b>`;return}let a=vals('A',4),tr=a[0]+a[3],det=a[0]*a[3]-a[1]*a[2];if(calc==='eigen'){let disc=tr*tr-4*det,s=Math.sqrt(Math.abs(disc)),l1=disc>=0?f((tr+s)/2):`${f(tr/2)} + ${f(s/2)}i`,l2=disc>=0?f((tr-s)/2):`${f(tr/2)} - ${f(s/2)}i`;calcResult.innerHTML=`<div class="step">det(λI-A) = λ² - (${f(tr)})λ + (${f(det)})</div><div class="step">Diskriminante = ${f(disc)}</div><div class="step">λ₁ = ${l1}, λ₂ = ${l2}</div><b>${tr<0&&det>0?'Asymptotisch stabil':'Nicht asymptotisch stabil'}</b>`}else if(calc==='control'){let b=vals('b',2),ab=[a[0]*b[0]+a[1]*b[1],a[2]*b[0]+a[3]*b[1]],d=b[0]*ab[1]-ab[0]*b[1];calcResult.innerHTML=`<div class="step">b = [${b}]ᵀ</div><div class="step">Ab = [${ab.map(f)}]ᵀ</div><div class="step">R = [[${b[0]}, ${f(ab[0])}], [${b[1]}, ${f(ab[1])}]]</div><div class="step">det(R) = ${f(d)}</div><b>${d?'Vollständig steuerbar':'Nicht vollständig steuerbar'}</b>`}else{let c=vals('C',2),ca=[c[0]*a[0]+c[1]*a[2],c[0]*a[1]+c[1]*a[3]],d=c[0]*ca[1]-c[1]*ca[0];calcResult.innerHTML=`<div class="step">C = [${c}]</div><div class="step">CA = [${ca.map(f)}]</div><div class="step">O = [[${c}], [${ca.map(f)}]]</div><div class="step">det(O) = ${f(d)}</div><b>${d?'Vollständig beobachtbar':'Nicht vollständig beobachtbar'}</b>`}};

const theory=[
['Systemkonzept und Modellbildung',`<p>Regelungstechnik beeinflusst einen zeitlich veränderlichen Prozess so, dass er einem gewünschten Verhalten folgt. Dafür braucht man ein mathematisches Modell, Messungen und eine rückgekoppelte Stellgröße.</p><div class="concept-grid"><div class="concept"><b>Stellgröße</b><p>Gezielt beeinflussbarer Eingang, etwa Heizleistung.</p></div><div class="concept"><b>Störgröße</b><p>Nicht kontrollierter Eingang, etwa Außentemperatur.</p></div><div class="concept"><b>Messgröße</b><p>Messtechnisch zugänglicher Ausgang.</p></div></div><div class="term-box"><b>Statisch oder dynamisch?</b> Beim Widerstand gilt sofort \(u=Ri\): statisch. Beim Kondensator hängt die Spannung von der vergangenen Stromzufuhr ab: dynamisch. Der Zustand fasst diese Vergangenheit kompakt zusammen.</div><div class="practice-box"><b>Praxisbeispiel:</b> Beim Feder-Masse-Dämpfer-System sind Position und Geschwindigkeit Zustände, die Kraft ist Eingang. Aus Newton folgt \(m\\ddot x+d\\dot x+kx=F\).</div>`],
['Linearität und Zeitinvarianz',`<p>Ein System ist <b>linear</b>, wenn das Superpositionsprinzip gilt: Skalieren und Addieren von Eingängen skaliert und addiert die Antworten. Es ist <b>zeitinvariant</b>, wenn eine Zeitverschiebung des Eingangs nur dieselbe Verschiebung der Antwort bewirkt.</p><div class="formula">\\[\\dot x=Ax+Bu,\\qquad y=Cx+Du\\]</div><div class="concept-grid"><div class="concept"><b>Nichtlinear</b><p>Produkte von Zuständen, Potenzen, sin, cos, log oder Wurzeln von Variablen.</p></div><div class="concept"><b>Zeitvariant</b><p>Die Zeit \(t\) steht ausdrücklich in Koeffizienten oder Funktionen.</p></div><div class="concept"><b>LTI</b><p>Linear und zeitinvariant: konstante Matrizen A, B, C, D.</p></div></div><div class="warning"><b>Erkennungsregel:</b> \(a(t)x\) ist linear, aber zeitvariant. \(ax_1x_2\) ist zeitinvariant, aber nichtlinear.</div>`],
['DGL, Transitionsmatrix und Lösung',`<p>Die Transitionsmatrix \(\Phi(t)=e^{At}\) transportiert einen Anfangszustand durch die Eigendynamik. Sie ist das Bindeglied zwischen Differentialgleichung und expliziter Zeitlösung.</p><div class="formula">\\[x(t)=e^{At}x_0+\\int_0^t e^{A(t-\\tau)}Bu(\\tau)\\,d\\tau\\]</div><div class="term-box"><b>Homogener Anteil:</b> \(e^{At}x_0\) ist die freie Bewegung aus dem Anfangszustand. <b>Partikulärer Anteil:</b> Das Integral beschreibt die erzwungene Bewegung durch den Eingang.</div><div class="practice-box"><b>Skalar und konstanter Eingang:</b> Für \(\dot x=\\lambda x+bu\) gilt bei \(\lambda\\ne0\): \(x(t)=e^{\\lambda t}x_0+\\frac{bu}{\\lambda}(e^{\\lambda t}-1)\). Für \(\lambda=0\): \(x(t)=x_0+but\).</div>`],
['Eigenbasis, Diagonalform und Jordanform',`<p>Eine Ähnlichkeitstransformation \(x=Vz\) ändert nur die Koordinaten, nicht das physikalische System. In günstigen Koordinaten entkoppelt sich die Dynamik.</p><div class="formula">\\[\\tilde A=V^{-1}AV,\\qquad e^{At}=Ve^{\\tilde A t}V^{-1}\\]</div><div class="concept-grid"><div class="concept"><b>Algebraische Vielfachheit</b><p>Wie oft ein Eigenwert Nullstelle des charakteristischen Polynoms ist.</p></div><div class="concept"><b>Geometrische Vielfachheit</b><p>Dimension des Eigenraums, also Anzahl unabhängiger Eigenvektoren.</p></div><div class="concept"><b>Diagonalisierbar</b><p>Für jeden Eigenwert stimmen beide Vielfachheiten überein.</p></div></div><div class="warning">Ist die geometrische Vielfachheit kleiner, fehlen Eigenvektoren. Dann benötigt man Hauptvektoren und die Jordansche Normalform.</div>`],
['Übertragungsfunktion und E/A-Stabilität',`<p>Die Übertragungsfunktion beschreibt das Verhalten vom Eingang zum Ausgang bei verschwindendem Anfangszustand. Interne Zustände sind dabei nicht direkt sichtbar.</p><div class="formula">\\[G(s)=C(sI-A)^{-1}B+D=\\frac{Y(s)}{U(s)}\\]</div><div class="term-box"><b>Pole</b> sind Nullstellen des Nenners und bestimmen die sichtbare Dynamik. <b>Nullstellen</b> sind Nullstellen des Zählers. Durch Pol-Nullstellen-Kürzung können instabile interne Moden im Ein-/Ausgangsverhalten verborgen bleiben.</div><div class="practice-box"><b>E/A-stabil:</b> Jeder beschränkte Eingang erzeugt einen beschränkten Ausgang. Für rationale Übertragungsfunktionen müssen alle Pole strikt negative Realteile besitzen.</div>`],
['Frequenzgang und Regelkreisglieder',`<p>Der Frequenzgang \(G(i\\omega)\) sagt, wie stark ein System eine Sinusschwingung einer bestimmten Frequenz verstärkt und um wie viel es deren Phase verschiebt.</p><div class="formula">\\[u=A_0\\sin(\\omega t)\\Rightarrow y=A_0|G(i\\omega)|\\sin(\\omega t+\\arg G(i\\omega))\\]</div><div class="concept-grid"><div class="concept"><b>Amplitudengang</b><p>\(|G(i\\omega)|\): Verstärkung je Frequenz.</p></div><div class="concept"><b>Phasengang</b><p>\(\arg G(i\\omega)\): Phasenverschiebung.</p></div><div class="concept"><b>Nyquist-Ortskurve</b><p>Kurve von \(G(i\\omega)\) in der komplexen Ebene.</p></div></div><div class="info">Reihenschaltung: \(G=G_1G_2\). Parallelschaltung: \(G=G_1+G_2\). Negative Rückkopplung: \(G=G_1/(1+G_1G_2)\).</div>`]
];
theory.forEach((x,i)=>theoryPlus.insertAdjacentHTML('beforeend',`<details class="chapter-card"${i===0?' open':''}><summary>${i+1}. ${x[0]}</summary><div class="chapter-body">${x[1]}</div></details>`));

const tuts=[
['Tutorium 1 · Mathematische Grundlagen','Offizielle Lösung vorhanden',[
['1.1 Eigenwerte, Eigenvektoren und LGS','Beginne bei Eigenwerten immer mit der Determinante. Beim LGS vergleiche Rang(A) und Rang([A|b]).','Für die gegebene obere Dreiecksstruktur entstehen die Eigenwerte \(1,2,3\). Eigenvektoren folgen jeweils aus \((A-\\lambda I)v=0\). Beim ersten rechten Vektor gibt es unendlich viele Lösungen, beim zweiten keine.','Das charakteristische Polynom faktorisiert zu \((\\lambda-1)(\\lambda-2)(\\lambda-3)\). Für jeden Eigenwert wird das homogene Gleichungssystem gelöst. Beim LGS gilt: Liegt \(b\) im Bild von A und besitzt A einen nichttrivialen Kern, gibt es unendlich viele Lösungen; liegt \(b\) nicht im Bild, existiert keine Lösung.'],
['1.2 Komplexe Zahlen','Kartesisch rechnen; für Eulerform Betrag und Winkel bestimmen.','Nutze \(z=r e^{i\\varphi}\) mit \(r=\\sqrt{x^2+y^2}\) und quadrantengerechtem Winkel.','Bei Produkten und Potenzen ist die Eulerform besonders praktisch: Beträge werden multipliziert beziehungsweise potenziert, Winkel addiert beziehungsweise vervielfacht.'],
['1.3 Gewöhnliche DGL','Zuerst homogene Lösung über den \(e^{\\lambda t}\)-Ansatz, dann Inhomogenität und Anfangswerte.','Die charakteristische Gleichung entscheidet zwischen reellen, mehrfachen und komplexen Lösungen.','Für komplexe Pole \(-1\\pm2i\) lautet die reelle Lösungsform \(e^{-t}(C_1\\cos2t+C_2\\sin2t)\). Bei einem doppelten Pol \(-1\) entsteht \((C_1t+C_2)e^{-t}\).']
]],
['Tutorium 2 · Systeme und Linearisierung','Eigene Musterlösungen',[
['2.1 Systemklassifikation','Suche zuerst nach Nichtlinearitäten, danach nach explizitem \(t\).','(i) nichtlinear und zeitvariant; (ii) linear und zeitvariant; (iii) linear und zeitinvariant; (iv) nichtlinear und zeitinvariant.','(i) enthält \(x_2^2\), \(\log u\) und \(a(t)\). (ii) Zustände und Eingang treten linear auf, aber Koeffizienten \(t,e^t\) hängen von der Zeit ab. (iii) nur konstante Koeffizienten. (iv) das Produkt \(x_1x_2\) ist nichtlinear, explizites \(t\) fehlt.'],
['2.2 Jacobi-Matrizen','Element \(J_{ij}\) ist die Ableitung der i-ten Funktion nach der j-ten Variable.','Für \(f_1=[\\sin(x_1)x_2^2, e^{-\\alpha x_1x_2}]^T\) entsteht eine 2×2-Matrix.','Zeile 1: \([\\cos(x_1)x_2^2,\,2x_2\\sin(x_1)]\). Zeile 2: \([-\\alpha x_2e^{-\\alpha x_1x_2},\,-\\alpha x_1e^{-\\alpha x_1x_2}]\). Danach bei Bedarf den Arbeitspunkt einsetzen.'],
['2.3 Ruhelagen und Linearisierung','Setze zuerst \(\dot x=0\), dann bilde A, B, C und D.','Für \(\dot x=a\\tan x\) sind bei \(a\\ne0\) die Ruhelagen \(x_R=k\\pi\); lokal gilt \(A=a\\sec^2(x_R)=a\).','Beim zweiten System folgt \(x_{1,R}=e^{-u_R}\) und \(x_{2,R}=\\pm e^{-u_R/2}\). Die Linearisierung hat \(A=[[1/x_{1,R},0],[-1,2x_{2,R}]]\), \(B=[1,0]^T\). Wegen der Dreiecksform sind die Eigenwerte \(1/x_{1,R}\) und \(2x_{2,R}\).'],
['2.4 Skalare Zustands-DGL','Variation der Konstanten oder direkt die bekannte LTI-Lösung nutzen.','Für \(\lambda\\ne0\): \(x(t)=e^{\\lambda t}x_0+\\frac{bu}{\\lambda}(e^{\\lambda t}-1)\).','Bei \(u=0\) entscheidet das Vorzeichen von \(\lambda\): positiv wächst, negativ klingt ab, \(\lambda=0\) bleibt konstant. Je größer \(|\\lambda|\), desto schneller die Änderung.']
]],
['Tutorium 3 · Transformation und Stabilität','Offizielle Lösung vorhanden',[
['3.1 Vielfachheiten','Bestimme erst algebraische, dann geometrische Vielfachheit über \(g=n-\\operatorname{rang}(A-\\lambda I)\).','Diagonalform ist genau dann möglich, wenn für jeden Eigenwert algebraische und geometrische Vielfachheit übereinstimmen.','Bei fehlenden unabhängigen Eigenvektoren wird die Jordanform benötigt. Komplexe Eigenwerte sind für reelle Matrizen stets konjugiert komplex.'],
['3.2 Transitionsmatrix','Baue V aus Eigenvektoren und berechne \(V^{-1}AV\).','In Diagonalkoordinaten werden die Eigenwerte einfach exponentiert.','Für \(A=[[-4,2],[-3,1]]\) sind die Eigenwerte \(-2,-1\), beispielsweise \(V=[[1,2],[1,3]]\). Dann \(\Phi(t)=V\\operatorname{diag}(e^{-2t},e^{-t})V^{-1}\).'],
['3.3 Stabilitätsanalyse','Bei Dreiecks- und Diagonalmatrizen Eigenwerte direkt ablesen.','Alle Realteile müssen strikt negativ sein.','Ein einzelner positiver Eigenwert macht das System instabil. Für komplexe Pole zählt nur der Realteil. Beim parametrischen Fall \(\lambda_2=2+a\) ist Stabilität genau für \(a<-2\) gegeben.']
]],
['Tutorium 4 · Regler und Beobachter','Eigene Musterlösungen',[
['4.1a Offene Stabilität','Bei oberer Dreiecksmatrix stehen Eigenwerte auf der Diagonalen.','Eigenwerte sind \(1,2,1\): Das offene System ist instabil.','Da alle drei Eigenwerte positive Realteile besitzen, wachsen die zugehörigen Moden. Eine Zustandsrückführung soll sie in die linke Halbebene verschieben.'],
['4.1b Steuerbarkeit','Berechne \(b,Ab,A^2b\) als Spalten.','\(\mathcal R=[[0,3,6],[0,2,6],[1,1,1]]\), \(\det\\mathcal R=6\\ne0\).','Der Rang ist 3. Damit ist das System vollständig steuerbar und alle drei Pole dürfen frei vorgegeben werden.'],
['4.1c Zustandsregler mit Ackermann','Gewünschte Pole \(-1,-2,-1\) ergeben \(p^*(\\lambda)=(\\lambda+1)^2(\\lambda+2)=\\lambda^3+4\\lambda^2+5\\lambda+2\).','Für \(u=-k^Tx\) ergibt sich \(k^T=[-4,18,8]\).','Setze \(p^*(A)=A^3+4A^2+5A+2I\) in Ackermann ein. Die Kontrolle von \(A-bk^T\) liefert die Pole \(-1,-1,-2\).'],
['4.2a Beobachtbarkeit mit Parametern','Stelle \(\mathcal O=[C;CA;CA^2]\) auf und faktorisiere die Determinante.','\(\det\\mathcal O=-3\\alpha^2\\beta\). Nicht beobachtbar für \(\alpha=0\) oder \(\beta=0\); \(\gamma\) ist dafür beliebig.','Die Determinante zeigt unmittelbar, welche Messanteile zwingend benötigt werden. Fehlt der Anteil von \(x_1\) oder \(x_2\), bleibt mindestens eine Mode unsichtbar.'],
['4.2b Zustandsbeobachter','Nutze die Dualität oder die Beobachter-Ackermann-Formel.','Für \(C=[1,1,0]\) und Pole \(-1,-2,-1\) ergibt sich \(l=[-36,44,-4]^T\).','\(\mathcal O=[[1,1,0],[1,2,5],[1,4,12]]\) besitzt Determinante \(-3\). Mit \(p^*(A)\mathcal O^{-1}e_3\) folgt \(l\). Kontrolle: \(A-lC\) hat Pole \(-1,-1,-2\).']
]]
];
function taskHTML(t,ti,qi,own){return `<div class="task"><h4>${t[0]} ${own?'<span class="own-solution">eigene Musterlösung</span>':''}</h4><div class="task-actions"><button data-task="tip-${ti}-${qi}">Tipp</button><button data-task="result-${ti}-${qi}">Ergebnis</button><button data-task="way-${ti}-${qi}">Lösungsweg</button></div><div id="tip-${ti}-${qi}" class="task-reveal">${t[1]}</div><div id="result-${ti}-${qi}" class="task-reveal"><b>${t[2]}</b></div><div id="way-${ti}-${qi}" class="task-reveal">${t[3]}</div></div>`}
tuts.forEach((t,i)=>tutorials.insertAdjacentHTML('beforeend',`<details class="tutorial"><summary>${t[0]} · ${t[1]}</summary><div class="tutorial-body">${t[2].map((q,j)=>taskHTML(q,i,j,i===1||i===3)).join('')}</div></details>`));
document.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.task).classList.toggle('show'));

const formulas=[
['LTI-Zustandsraum','\\(\\dot x=Ax+Bu,\\quad y=Cx+Du\\)','Grundmodell für lineare zeitinvariante Systeme.','A, B, C und D müssen konstante, dimensionskompatible Matrizen sein.'],
['Linearisierung','\\(A=\\left.\\partial f/\\partial x\\right|_R,\\ B=\\left.\\partial f/\\partial u\\right|_R\\)','Lokale lineare Näherung um einen Arbeitspunkt.','Arbeitspunkt muss \(f(x_R,u_R)=0\) erfüllen.'],
['Transitionsmatrix','\\(\\Phi(t)=e^{At},\\quad x(t)=\\Phi(t)x_0+\\int_0^t\\Phi(t-\\tau)Bu(\\tau)d\\tau\\)','Explizite Lösung einer LTI-Zustandsgleichung.','Für zeitinvariantes A.'],
['Charakteristisches Polynom','\\(p(\\lambda)=\\det(\\lambda I-A)\\)','Eigenwerte und Stabilität bestimmen.','Nullstellen von p sind Eigenwerte.'],
['Stabilität','\\(\\operatorname{Re}(\\lambda_i)<0\\ \\forall i\\)','Asymptotische Stabilität kontinuierlicher LTI-Systeme.','Gilt für die autonome Zustandsdynamik.'],
['Steuerbarkeit','\\(\\mathcal R=[B,AB,\\ldots,A^{n-1}B],\\ \\operatorname{rang}\\mathcal R=n\\)','Prüft, ob Eingänge alle Zustände erreichen.','Kalman-Kriterium für LTI-Systeme.'],
['Beobachtbarkeit','\\(\\mathcal O=[C;CA;\\ldots;CA^{n-1}],\\ \\operatorname{rang}\\mathcal O=n\\)','Prüft, ob Ausgänge alle Zustände sichtbar machen.','Kalman-Kriterium für LTI-Systeme.'],
['Ackermann Regler','\\(k^T=e_n^T\\mathcal R^{-1}p^*(A)\\)','Beliebige Polvorgabe durch Zustandsrückführung.','SISO und vollständig steuerbar.'],
['Ackermann Beobachter','\\(l=p^*(A)\\mathcal O^{-1}e_n\\)','Beliebige Pole der Fehlerdynamik.','SISO und vollständig beobachtbar.'],
['Übertragungsfunktion','\\(G(s)=C(sI-A)^{-1}B+D\\)','Eingangs-/Ausgangsverhalten im Laplace-Bereich.','Verschwindender Anfangszustand.'],
['Rückkopplung','\\(G_{cl}(s)=G_1(s)/(1+G_1(s)G_2(s))\\)','Gesamtübertragung bei negativer Rückkopplung.','Vorzeichen am Summationspunkt beachten.'],
['Frequenzgang','\\(G(i\\omega)=|G(i\\omega)|e^{i\\arg G(i\\omega)}\\)','Amplitude und Phase sinusförmiger Antworten.','Eingeschwungener Zustand und E/A-Stabilität.'],
['Laplace-Ableitung','\\(\\mathcal L\\{f^{(n)}\\}=s^nF(s)-s^{n-1}f(0^+)-\\cdots-f^{(n-1)}(0^+)\\)','Differentialgleichungen in algebraische Gleichungen umwandeln.','Anfangswerte vollständig einsetzen.'],
['Endwertsatz','\\(\\lim_{t\\to\\infty}f(t)=\\lim_{s\\to0}sF(s)\\)','Stationären Endwert direkt bestimmen.','Endwert muss existieren; Stabilitätsbedingungen prüfen.']
];
function renderFormulas(q=''){formulaList.innerHTML='';formulas.filter(x=>x.join(' ').toLowerCase().includes(q.toLowerCase())).forEach(x=>formulaList.insertAdjacentHTML('beforeend',`<article class="formula-card"><h3>${x[0]}</h3><div class="math">${x[1]}</div><p class="use">${x[2]}</p><div class="condition"><b>Voraussetzung:</b> ${x[3]}</div></article>`));if(window.MathJax?.typesetPromise)MathJax.typesetPromise([formulaList])}renderFormulas();formulaSearch.oninput=e=>renderFormulas(e.target.value);
if(window.MathJax?.typesetPromise)MathJax.typesetPromise([theoryPlus,tutorials,formulaList]);
